# 번역 파일의 위치 명시(번역파일 확장자는 .arb)
# 생성된 코드는 어디에 저장되어야 하는지 명시
arb-dir: lib/intl

# 앱의 기본 언어가 들어있는 파일이 무엇인지 알려줘야 함
# 앞부분은 사용자가 원하는 것_언어코드.arb 형태로 알려줘야 함
template-arb-file: intl_en.arb

# 번역본 파일이 어떤 곳에 생성되어야 하는 지 적어줘야 함
output-localization-file: intl_generated.dart
