// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW_EqQVct6bD-zJjz5BdmKQ9rlxepppP4',
    appId: '1:920008271510:web:d165a760b824c263e744b7',
    messagingSenderId: '920008271510',
    projectId: 'tiktok-verobeach7',
    authDomain: 'tiktok-verobeach7.firebaseapp.com',
    storageBucket: 'tiktok-verobeach7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXXoeZWGQu8WEzv61evUDDg26pmpnT0SU',
    appId: '1:920008271510:android:c61fc0d05b172518e744b7',
    messagingSenderId: '920008271510',
    projectId: 'tiktok-verobeach7',
    storageBucket: 'tiktok-verobeach7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKY37ZnC0ic9pVbskpuNhblKNf8jOp61o',
    appId: '1:920008271510:ios:b42c7bdc75f6c948e744b7',
    messagingSenderId: '920008271510',
    projectId: 'tiktok-verobeach7',
    storageBucket: 'tiktok-verobeach7.appspot.com',
    iosBundleId: 'co.mazingaz.tiktokClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKY37ZnC0ic9pVbskpuNhblKNf8jOp61o',
    appId: '1:920008271510:ios:18e646edcc70e201e744b7',
    messagingSenderId: '920008271510',
    projectId: 'tiktok-verobeach7',
    storageBucket: 'tiktok-verobeach7.appspot.com',
    iosBundleId: 'com.example.tiktokClone.RunnerTests',
  );
}
